version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Almaty"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:10"
      timezone: "Asia/Almaty"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
