# aidgraph/exporters/word_builder.py

from __future__ import annotations

from typing import Dict, Any, List
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from io import BytesIO

def build_docx_from_toc(toc_draft: Dict[str, Any], donor_id: str) -> bytes:
    """Конвертирует ToC draft в форматированный .docx."""
    doc = Document()
    
    title = doc.add_heading(f"Theory of Change — {donor_id}", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph(f"Donor: {donor_id}")
    doc.add_paragraph(f"Generated by: AidGraph")
    
    if "toc" in toc_draft:
        toc_content = toc_draft["toc"]
        
        if "brief" in toc_content:
            doc.add_heading("Overview", level=1)
            doc.add_paragraph(toc_content["brief"])
        
        if "objectives" in toc_content:
            doc.add_heading("Development Objectives", level=1)
            for obj in toc_content["objectives"]:
                doc.add_heading(obj.get("title", "Untitled"), level=2)
                doc.add_paragraph(obj.get("description", ""))
                
                if "citation" in obj:
                    p = doc.add_paragraph()
                    p.add_run(f"Citation: {obj['citation']}").italic = True
    
    if "indicators" in toc_draft:
        doc.add_heading("Key Indicators", level=1)
        for ind in toc_draft["indicators"]:
            doc.add_paragraph(f"• {ind.get('name', 'Unknown')}", style='List Bullet')
            if "justification" in ind:
                doc.add_paragraph(f"  Justification: {ind['justification']}", style='Intense Quote')
    
    bio = BytesIO()
    doc.save(bio)
    bio.seek(0)
    return bio.read()

def save_docx_to_file(toc_draft: Dict[str, Any], donor_id: str, 
                      output_path: str) -> str:
    """Сохраняет .docx на диск."""
    content = build_docx_from_toc(toc_draft, donor_id)
    with open(output_path, 'wb') as f:
        f.write(content)
    return output_path
